### ISSUE TITLE
Failed to Activate Wiki.JS for user 

### ISSUE THREAD

**Issue by paulipa** [pvyParts/allianceauth-wiki-js#4]
Wiki.js 2.5.201
allianceauth-wiki-js 0.0.4

When trying to activate the service you get an error and you are not forwarded to the password page. However the user is created on the wiki even when it returns an error. If after this you either click on the reactivate or deactivate + activate buttons the activation works as intended and the user is able to log in.
```
[23/Jun/2021 07:42:38] INFO [wikijs.manager:228] Creating new user for Ikarus_Cesaille
[23/Jun/2021 07:42:38] ERROR [wikijs.manager:243] HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/home/allianceserver/venv/auth/lib/python3.6/site-packages/wikijs/manager.py", line 238, in activate_user
    self._update_password(uid, password)
  File "/home/allianceserver/venv/auth/lib/python3.6/site-packages/wikijs/manager.py", line 154, in _update_password
    "password":password
  File "/home/allianceserver/venv/auth/lib/python3.6/site-packages/graphqlclient/client.py", line 11, in execute
    return self._send(query, variables)
  File "/home/allianceserver/venv/auth/lib/python3.6/site-packages/graphqlclient/client.py", line 34, in _send
    raise e
  File "/home/allianceserver/venv/auth/lib/python3.6/site-packages/graphqlclient/client.py", line 29, in _send
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
[23/Jun/2021 07:42:38] ERROR [wikijs.views:41] Failed to Activate Wiki.JS for user Ikarus_Cesaille
```

**Comment by pvyParts** [comment]
This should be fixed in 0.0.5 let me know if you still have issues.
